sudo: false
notifications:
  email: false
language: python
cache: pip
python:
  - "3.5"
  - "3.6"
before_install:
  - pip install http://download.pytorch.org/whl/cu80/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl
install:
  - pip install -r requirements.txt
  - pip install .
script: nosetests tests
